version: '3'
services:
  mongodb:
    image: mongo:4.2
    networks:
      - graylog
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:4.3
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_HTTP_ENABLE_CORS=true
      - GRAYLOG_HTTP_ENABLE_GZIP=true
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_REST_LISTEN_URI=http://0.0.0.0:9000/api/
      - GRAYLOG_WEB_LISTEN_URI=http://0.0.0.0:9000/
      - GRAYLOG_WEB_ENABLE=true
      - GRAYLOG_INPUTS_0_TYPE=org.graylog2.inputs.gelf.udp.GELFUDPInput
      - GRAYLOG_INPUTS_0_TITLE=GELF UDP
      - GRAYLOG_INPUTS_0_BIND_ADDRESS=0.0.0.0
      - GRAYLOG_INPUTS_0_PORT=12202
      - GRAYLOG_INPUTS_0_GLOBAL=true
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
      - GRAYLOG_IS_MASTER=true
      - GRAYLOG_INPUTS_0_RECV_BUFFER_SIZE=1048576
    networks:
      - graylog
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "12202:12202/udp"
    volumes:
      - graylog_data:/usr/share/graylog/data


  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - graylog
    depends_on:
      - graylog
    restart: always

networks:
  graylog:
    driver: bridge

volumes:
  mongodb_data:
  elasticsearch_data:
  graylog_data:
